function A_disc = calc_A_disc(in1,u,dt,in4)
%CALC_A_DISC
%    A_DISC = CALC_A_DISC(IN1,U,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Oct-2021 13:27:14

g = in4(:,4);
ll = in4(:,3);
mc = in4(:,1);
mp = in4(:,2);
theta = in1(2,:);
theta_dot = in1(4,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = mc+mp;
t5 = theta_dot.^2;
t8 = 1.0./ll;
t6 = t3.^2;
t7 = g.*t2;
t9 = ll.*t5;
t10 = mp.*t6;
t12 = t7+t9;
t11 = mc+t10;
t13 = 1.0./t11;
t14 = t13.^2;
A_disc = reshape([1.0,0.0,0.0,0.0,0.0,1.0,-dt.*t13.*(g.*t10-mp.*t2.*t12)-dt.*mp.*t2.*t3.*t14.*(u+mp.*t3.*t12).*2.0,-dt.*t8.*t13.*(t4.*t7-t9.*t10-t3.*u+mp.*t2.^2.*t9)+dt.*mp.*t2.*t3.*t8.*t14.*(t2.*u+g.*t3.*t4+mp.*t2.*t3.*t9).*2.0,dt,0.0,1.0,0.0,0.0,dt,dt.*ll.*mp.*t3.*t13.*theta_dot.*2.0,dt.*mp.*t2.*t3.*t13.*theta_dot.*-2.0+1.0],[4,4]);
