function f_disc = calc_f_disc(in1,in2,dt,in4)
%CALC_F_DISC
%    F_DISC = CALC_F_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Oct-2021 23:43:10

px = in1(1,:);
py = in1(2,:);
theta = in1(4,:);
theta_dot = in2(2,:);
v = in1(3,:);
v_dot = in2(1,:);
f_disc = [px+dt.*v.*cos(theta);py+dt.*v.*sin(theta);v+dt.*v_dot;theta+dt.*theta_dot];
