function B_disc = calc_B_disc(in1,u,dt,in4)
%CALC_B_DISC
%    B_DISC = CALC_B_DISC(IN1,U,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Oct-2021 13:27:15

ll = in4(:,3);
mc = in4(:,1);
mp = in4(:,2);
theta = in1(2,:);
t2 = sin(theta);
t3 = t2.^2;
t4 = mp.*t3;
t5 = mc+t4;
t6 = 1.0./t5;
B_disc = [0.0;0.0;dt.*t6;-(dt.*t6.*cos(theta))./ll];
