function f_disc = calc_f_disc(in1,u,dt,in4)
%CALC_F_DISC
%    F_DISC = CALC_F_DISC(IN1,U,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Oct-2021 13:27:14

g = in4(:,4);
ll = in4(:,3);
mc = in4(:,1);
mp = in4(:,2);
theta = in1(2,:);
theta_dot = in1(4,:);
x = in1(1,:);
x_dot = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = theta_dot.^2;
t5 = t3.^2;
t6 = mp.*t5;
t7 = mc+t6;
t8 = 1.0./t7;
f_disc = [x+dt.*x_dot;theta+dt.*theta_dot;x_dot+dt.*t8.*(u+mp.*t3.*(g.*t2+ll.*t4));theta_dot-(dt.*t8.*(t2.*u+g.*t3.*(mc+mp)+ll.*mp.*t2.*t3.*t4))./ll];
