function f_disc = calc_f_disc(in1,in2,dt,in4)
%CALC_F_DISC
%    F_DISC = CALC_F_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Oct-2021 17:00:25

J_x = in4(:,1);
J_y = in4(:,2);
J_z = in4(:,3);
delta_b = in2(3,:);
delta_f = in2(1,:);
delta_l = in2(4,:);
delta_r = in2(2,:);
ell = in4(:,6);
g = in4(:,5);
k_1 = in4(:,7);
k_2 = in4(:,8);
m = in4(:,4);
p = in1(10,:);
phi = in1(4,:);
psi = in1(6,:);
px = in1(1,:);
py = in1(2,:);
pz = in1(3,:);
q = in1(11,:);
r = in1(12,:);
theta = in1(5,:);
u = in1(7,:);
v = in1(8,:);
w = in1(9,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = tan(theta);
t9 = delta_b.*k_1;
t10 = delta_f.*k_1;
t11 = delta_l.*k_1;
t12 = delta_r.*k_1;
t13 = -J_z;
t14 = 1.0./J_x;
t15 = 1.0./J_y;
t16 = 1.0./J_z;
t17 = 1.0./t4;
f_disc = [px+dt.*(-v.*(t2.*t6-t3.*t5.*t7)+w.*(t5.*t6+t2.*t3.*t7)+t3.*t4.*u);py+dt.*(v.*(t2.*t3+t5.*t6.*t7)-w.*(t3.*t5-t2.*t6.*t7)+t4.*t6.*u);pz+dt.*(-t7.*u+t4.*t5.*v+t2.*t4.*w);phi+dt.*(p+q.*t5.*t8+r.*t2.*t8);theta+dt.*(q.*t2-r.*t5);psi+dt.*(q.*t5.*t17+r.*t2.*t17);u-dt.*(g.*t7+q.*w-r.*v);v+dt.*(p.*w-r.*u+g.*t4.*t5);w-dt.*(p.*v-q.*u+(t9+t10+t11+t12)./m-g.*t2.*t4);p+dt.*(ell.*t14.*(t11-t12)+q.*r.*t14.*(J_y+t13));q-dt.*(ell.*t15.*(t9-t10)+p.*r.*t15.*(J_x+t13));r-dt.*(t16.*(delta_b.*k_2+delta_f.*k_2-delta_l.*k_2-delta_r.*k_2)-p.*q.*t16.*(J_x-J_y))];
