function B_disc = calc_B_disc(in1,in2,dt,in4)
%CALC_B_DISC
%    B_DISC = CALC_B_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Oct-2021 17:27:37

B_disc = reshape([0.0,0.0,dt,0.0,0.0,0.0,0.0,dt],[4,2]);
