function A_disc = calc_A_disc(in1,in2,dt,in4)
%CALC_A_DISC
%    A_DISC = CALC_A_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Oct-2021 00:43:33

theta = in1(4,:);
v = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
A_disc = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,dt.*t2,dt.*t3,1.0,0.0,-dt.*t3.*v,dt.*t2.*v,0.0,1.0],[4,4]);
