function A_disc = calc_A_disc(in1,u,dt,in4)
%CALC_A_DISC
%    A_DISC = CALC_A_DISC(IN1,U,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Nov-2021 12:46:28

L = in4(:,3);
g = in4(:,2);
theta = in1(1,:);
A_disc = reshape([1.0,-(dt.*g.*cos(theta))./L,dt,1.0],[2,2]);
