function f = calc_f(in1,in2,in3)
%CALC_F
%    F = CALC_F(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Oct-2021 17:00:25

J_x = in3(:,1);
J_y = in3(:,2);
J_z = in3(:,3);
delta_b = in2(3,:);
delta_f = in2(1,:);
delta_l = in2(4,:);
delta_r = in2(2,:);
ell = in3(:,6);
g = in3(:,5);
k_1 = in3(:,7);
k_2 = in3(:,8);
m = in3(:,4);
p = in1(10,:);
phi = in1(4,:);
psi = in1(6,:);
q = in1(11,:);
r = in1(12,:);
theta = in1(5,:);
u = in1(7,:);
v = in1(8,:);
w = in1(9,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = tan(theta);
t9 = delta_b.*k_1;
t10 = delta_f.*k_1;
t11 = delta_l.*k_1;
t12 = delta_r.*k_1;
t13 = -J_z;
t14 = 1.0./J_x;
t15 = 1.0./J_y;
t16 = 1.0./J_z;
t17 = 1.0./t4;
f = [-v.*(t2.*t6-t3.*t5.*t7)+w.*(t5.*t6+t2.*t3.*t7)+t3.*t4.*u;v.*(t2.*t3+t5.*t6.*t7)-w.*(t3.*t5-t2.*t6.*t7)+t4.*t6.*u;-t7.*u+t4.*t5.*v+t2.*t4.*w;p+q.*t5.*t8+r.*t2.*t8;q.*t2-r.*t5;q.*t5.*t17+r.*t2.*t17;-g.*t7-q.*w+r.*v;p.*w-r.*u+g.*t4.*t5;-p.*v+q.*u-(t9+t10+t11+t12)./m+g.*t2.*t4;ell.*t14.*(t11-t12)+q.*r.*t14.*(J_y+t13);-ell.*t15.*(t9-t10)-p.*r.*t15.*(J_x+t13);-t16.*(delta_b.*k_2+delta_f.*k_2-delta_l.*k_2-delta_r.*k_2)+p.*q.*t16.*(J_x-J_y)];
