function f1_disc = calc_f1_disc(in1,in2,dt,in4)
%CALC_F1_DISC
%    F1_DISC = CALC_F1_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:19:18

g = in4(:,2);
m = in4(:,1);
u_x = in2(1,:);
u_y = in2(2,:);
x = in1(1,:);
x_dot = in1(3,:);
y = in1(2,:);
y_dot = in1(4,:);
t2 = 1.0./m;
f1_disc = [x+dt.*x_dot;y+dt.*y_dot;x_dot+dt.*t2.*u_x;y_dot+dt.*t2.*(u_y-g.*m)];
