function salt1 = calc_salt12(in1,in2,in3)
%CALC_SALT12
%    SALT1 = CALC_SALT12(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:19:19

x = in1(1,:);
x_dot = in1(3,:);
y = in1(2,:);
y_dot = in1(4,:);
t2 = x.*x_dot;
t3 = y.*y_dot;
t4 = x.^2;
t5 = x.^3;
t6 = y.^2;
t7 = y.^3;
t8 = y_dot.*5.0;
t9 = y.*1.0e+1;
t10 = y-5.0;
t14 = x_dot.*1.25e+2;
t17 = x_dot.*y.*7.5e+1;
t11 = -t8;
t12 = t7.*x_dot;
t13 = t5.*y_dot;
t15 = -t9;
t16 = t10.^2;
t18 = -t17;
t20 = t6.*x_dot.*1.5e+1;
t19 = -t12;
t21 = t2+t3+t11;
t22 = t4+t6+t15+2.5e+1;
t23 = 1.0./t22;
t24 = t23.^2;
t25 = t4.*t23;
t26 = t10.*t23.*x;
t27 = t16.*t23;
t28 = -t26;
salt1 = reshape([t27,t28,-t16.*t21.*t24,t24.*(t13+t14+t18+t19+t20-t3.*x.*2.0e+1+x.*y_dot.*5.0e+1+t3.*x.*y.*2.0),t28,t25,-t24.*(t13+t14+t18+t19+t20+t2.*x.*1.0e+1-t2.*x.*y.*2.0),-t4.*t21.*t24,0.0,0.0,t27,t28,0.0,0.0,t28,t25],[4,4]);
