function DR1 = calc_Dr12(in1,in2,in3)
%CALC_DR12
%    DR1 = CALC_DR12(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:19:16

x = in1(1,:);
x_dot = in1(3,:);
y = in1(2,:);
y_dot = in1(4,:);
t2 = x.*y_dot;
t3 = x_dot.*y;
t4 = x.^2;
t5 = x_dot.*5.0;
t6 = y.*2.0;
t7 = y.^2;
t8 = y.*1.0e+1;
t9 = y-5.0;
t10 = -t3;
t11 = -t8;
t12 = t6-1.0e+1;
t13 = t2+t5+t10;
t14 = t4+t7+t11+2.5e+1;
t15 = 1.0./t14;
t16 = t15.^2;
t17 = t9.*t15.*x;
t19 = t13.*t15;
t18 = -t17;
DR1 = reshape([1.0,0.0,-t9.*t15.*y_dot+t9.*t13.*t16.*x.*2.0,t19+t2.*t15-t4.*t13.*t16.*2.0,0.0,1.0,-t19+t9.*t15.*x_dot+t9.*t12.*t13.*t16,-t15.*x.*x_dot-t12.*t13.*t16.*x,0.0,0.0,t9.^2.*t15,t18,0.0,0.0,t18,t4.*t15],[4,4]);
