function salt2 = calc_salt21(in1,in2,in3)
%CALC_SALT21
%    SALT2 = CALC_SALT21(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:00:25

salt2 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
