function G2 = calc_g21(in1,uy,in3)
%CALC_G21
%    G2 = CALC_G21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Nov-2021 11:49:20

y_dot = in1(2,:);
G2 = -y_dot;
