function R2 = calc_r21(in1,in2,in3)
%CALC_R21
%    R2 = CALC_R21(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Nov-2021 19:55:06

q1 = in1(1,:);
q2 = in1(2,:);
q1_dot = in1(3,:);
q2_dot = in1(4,:);
R2 = [q1;q2;q1_dot;q2_dot];
