function B_lin1_disc = calc_B_lin1_disc(in1,in2,dt,in4)
%CALC_B_LIN1_DISC
%    B_LIN1_DISC = CALC_B_LIN1_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Nov-2021 19:55:10

L1 = in4(:,2);
L2 = in4(:,4);
m1 = in4(:,1);
m2 = in4(:,3);
q2 = in1(2,:);
t2 = cos(q2);
t3 = L1.^2;
t4 = L2.^2;
t7 = 1.0./m2;
t5 = t2.^2;
t6 = 1.0./t4;
t8 = m1.*t3.*4.0;
t9 = m2.*t4.*4.0;
t10 = m2.*t3.*1.2e+1;
t11 = m2.*t3.*t5.*9.0;
t12 = -t11;
t13 = t8+t10+t12;
t14 = 1.0./t13;
B_lin1_disc = reshape([0.0,0.0,dt.*t14.*1.2e+1,dt.*t6.*t7.*t14.*(t9+L1.*L2.*m2.*t2.*6.0).*-3.0,0.0,0.0,(dt.*t14.*(L2.*4.0+L1.*t2.*6.0).*-3.0)./L2,dt.*t6.*t7.*t14.*(t8+t9+t10+L1.*L2.*m2.*t2.*1.2e+1).*3.0],[4,2]);
