function out1 = calc_A_lin1(in1,in2,in3)
%CALC_A_LIN1
%    OUT1 = CALC_A_LIN1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:19:17

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[4,4]);
