function out1 = calc_B_lin2(in1,uy,in3)
%CALC_B_LIN2
%    OUT1 = CALC_B_LIN2(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 01:22:01

m = in3(:,1);
out1 = [0.0;1.0./m];
