function G1 = calc_a1(in1,in2,in3)
%CALC_A1
%    G1 = CALC_A1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:01:44

x = in1(1,:);
y = in1(2,:);
G1 = (y-5.0).^2+x.^2-4.0;
