function DtG1 = calc_Dtg12(in1,uy,in3)
%CALC_DTG12
%    DTG1 = CALC_DTG12(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2021 00:01:27

DtG1 = 0.0;
