function G2 = calc_a2(in1,in2,in3)
%CALC_A2
%    G2 = CALC_A2(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:19:17

g = in3(:,2);
m = in3(:,1);
u_x = in2(1,:);
u_y = in2(2,:);
x = in1(1,:);
x_dot = in1(3,:);
y = in1(2,:);
y_dot = in1(4,:);
G2 = (u_y.*-5.0+g.*m.*5.0+u_x.*x+u_y.*y+m.*x_dot.^2+m.*y_dot.^2-g.*m.*y)./(y.*-2.0e+1+x.^2.*2.0+y.^2.*2.0+5.0e+1);
