function G1 = calc_g12(in1,uy,in3)
%CALC_G12
%    G1 = CALC_G12(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 01:22:00

y = in1(1,:);
G1 = y;
