function salt2 = calc_salt21(in1,uy,in3)
%CALC_SALT21
%    SALT2 = CALC_SALT21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 01:22:01

salt2 = reshape([1.0,0.0,0.0,1.0],[2,2]);
