function R1 = calc_r12(in1,uy,in3)
%CALC_R12
%    R1 = CALC_R12(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2021 00:01:27

e = in3(:,3);
y = in1(1,:);
y_dot = in1(2,:);
R1 = [y;-e.*y_dot];
