function G2 = calc_a2(in1,uy,in3)
%CALC_A2
%    G2 = CALC_A2(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 01:22:01

y_dot = in1(2,:);
G2 = y_dot;
