function R1 = calc_r12(in1,in2,in3)
%CALC_R12
%    R1 = CALC_R12(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Nov-2021 19:55:05

L1 = in3(:,2);
L2 = in3(:,4);
m1 = in3(:,1);
m2 = in3(:,3);
q1 = in1(1,:);
q2 = in1(2,:);
q1_dot = in1(3,:);
q2_dot = in1(4,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = q1+q2;
t5 = L1.^2;
t6 = L2.^2;
t9 = 1.0./L1;
t7 = t2.^2;
t8 = cos(t4);
t10 = m2.*t7;
t11 = t8.^2;
t14 = m2.*t2.*t3.*t8.*3.0;
t12 = m1.*t11;
t13 = m2.*t11.*3.0;
t15 = -t14;
t16 = t10+t12+t13+t15;
t17 = 1.0./t16;
R1 = [q1;q2;(t9.*t17.*(L1.*q1_dot.*t12.*2.0+L2.*q1_dot.*t3.*t13+L2.*q2_dot.*t3.*t13+L1.*m2.*q1_dot.*t11.*6.0-L2.*m2.*q1_dot.*t2.*t8.*2.0-L2.*m2.*q2_dot.*t2.*t8.*2.0-L1.*m2.*q1_dot.*t2.*t3.*t8.*3.0))./2.0;(t9.*t17.*(q1_dot.*t3.*t5.*t10.*-3.0+q1_dot.*t3.*t6.*t13+q2_dot.*t3.*t6.*t13-L1.*L2.*q1_dot.*t10.*2.0-L1.*L2.*q2_dot.*t10.*2.0+L1.*L2.*q1_dot.*t12.*2.0+L1.*L2.*q2_dot.*t14+L1.*L2.*m2.*q1_dot.*t11.*6.0+m1.*q1_dot.*t2.*t5.*t8.*2.0+m2.*q1_dot.*t2.*t5.*t8.*6.0-m2.*q1_dot.*t2.*t6.*t8.*2.0-m2.*q2_dot.*t2.*t6.*t8.*2.0).*(-1.0./2.0))./L2];
