function B_lin2_disc = calc_B_lin2_disc(in1,in2,dt,in4)
%CALC_B_LIN2_DISC
%    B_LIN2_DISC = CALC_B_LIN2_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:00:25

m = in4(:,1);
x = in1(1,:);
y = in1(2,:);
t2 = x.^2;
t3 = y.^2;
t4 = m.*2.5e+1;
t5 = y-5.0;
t6 = m.*y.*1.0e+1;
t7 = m.*t2;
t8 = m.*t3;
t9 = -t6;
t10 = t4+t7+t8+t9;
t11 = 1.0./t10;
t12 = dt.*t5.*t11.*x;
t13 = -t12;
B_lin2_disc = reshape([0.0,0.0,dt.*t5.^2.*t11,t13,0.0,0.0,t13,dt.*t2.*t11],[4,2]);
