function DtG2 = calc_Dtg21(in1,in2,in3)
%CALC_DTG21
%    DTG2 = CALC_DTG21(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Nov-2021 19:55:07

DtG2 = 0.0;
