function DtG2 = calc_Dtg21(in1,uy,in3)
%CALC_DTG21
%    DTG2 = CALC_DTG21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2021 00:01:27

DtG2 = 0.0;
