function A_lin2_disc = calc_A_lin2_disc(in1,in2,dt,in4)
%CALC_A_LIN2_DISC
%    A_LIN2_DISC = CALC_A_LIN2_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:01:45

g = in4(:,2);
m = in4(:,1);
u_x = in2(1,:);
u_y = in2(2,:);
x = in1(1,:);
x_dot = in1(3,:);
y = in1(2,:);
y_dot = in1(4,:);
t2 = g.*m;
t3 = x.^2;
t4 = x_dot.^2;
t5 = y.*2.0;
t6 = y.^2;
t7 = y_dot.^2;
t9 = m.*1.0e+1;
t10 = m.*2.5e+1;
t11 = y.*1.0e+1;
t12 = y-5.0;
t16 = m.*y.*-2.0;
t22 = m.*y.*-1.0e+1;
t8 = m.*t5;
t13 = -t2;
t14 = t4.*2.0;
t15 = t7.*2.0;
t17 = t9.*y;
t18 = m.*t3;
t19 = m.*t6;
t20 = -t11;
t21 = t12.^2;
t24 = t5-1.0e+1;
t25 = t9+t16;
t23 = t13+u_y;
t26 = t14+t15;
t27 = t3+t6+t20+2.5e+1;
t30 = t10+t18+t19+t22;
t28 = 1.0./t27;
t31 = 1.0./t30;
t29 = t28.^2;
t32 = t31.^2;
t33 = (t26.*t28)./2.0;
A_lin2_disc = reshape([1.0,0.0,-dt.*(t33-t3.*t26.*t29-t12.*t31.*(t2-u_y)+t12.*t18.*t32.*(t2-u_y).*2.0+m.*t21.*t32.*u_x.*x.*2.0),dt.*(-t12.*t31.*u_x-t31.*x.*(t2-u_y).*2.0+t12.*t18.*t32.*u_x.*2.0+t12.*t26.*t29.*x+m.*t32.*x.^3.*(t2-u_y).*2.0),0.0,1.0,dt.*(t24.*t31.*u_x+t31.*x.*(t2-u_y)+t21.*t25.*t32.*u_x+(t24.*t26.*t29.*x)./2.0+t12.*t25.*t32.*x.*(t2-u_y)),-dt.*(t33+t31.*u_x.*x-(t12.*t24.*t26.*t29)./2.0+t3.*t25.*t32.*(t2-u_y)+t12.*t25.*t32.*u_x.*x),dt,0.0,dt.*t28.*x.*x_dot.*-2.0+1.0,dt.*t12.*t28.*x_dot.*-2.0,0.0,dt,dt.*t28.*x.*y_dot.*-2.0,dt.*t12.*t28.*y_dot.*-2.0+1.0],[4,4]);
