function B_lin2_disc = calc_B_lin2_disc(in1,uy,dt,in4)
%CALC_B_LIN2_DISC
%    B_LIN2_DISC = CALC_B_LIN2_DISC(IN1,UY,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Nov-2021 11:49:21

m = in4(:,1);
B_lin2_disc = [0.0;dt./m];
