function A_lin2_disc = calc_A_lin2_disc(in1,uy,dt,in4)
%CALC_A_LIN2_DISC
%    A_LIN2_DISC = CALC_A_LIN2_DISC(IN1,UY,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2021 00:01:28

A_lin2_disc = reshape([1.0,0.0,dt,1.0],[2,2]);
