function B_lin2_disc = calc_B_lin2_disc(in1,in2,dt,in4)
%CALC_B_LIN2_DISC
%    B_LIN2_DISC = CALC_B_LIN2_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Nov-2021 19:55:10

L1 = in4(:,2);
L2 = in4(:,4);
m1 = in4(:,1);
m2 = in4(:,3);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = q1+q2;
t5 = L2.^2;
t8 = 1.0./L1.^2;
t6 = t2.^2;
t7 = cos(t4);
t9 = 1.0./t5;
t10 = m2.*t6;
t11 = t7.^2;
t15 = m2.*t2.*t3.*t7.*3.0;
t12 = m1.*t11;
t13 = m2.*t11.*3.0;
t14 = t5.*t11.*6.0;
t16 = -t15;
t17 = t10+t12+t13+t16;
t18 = 1.0./t17;
B_lin2_disc = reshape([0.0,0.0,dt.*t8.*t11.*t18.*3.0,dt.*t8.*t9.*t18.*(t14+L1.*L2.*t2.*t7.*6.0).*(-1.0./2.0),0.0,0.0,(dt.*t8.*t18.*(L2.*t11.*6.0+L1.*t2.*t7.*6.0).*(-1.0./2.0))./L2,(dt.*t8.*t9.*t18.*(t14+(t6.*6.0)./t8+L1.*L2.*t2.*t7.*1.2e+1))./2.0],[4,2]);
