function DR2 = calc_Dr21(in1,uy,in3)
%CALC_DR21
%    DR2 = CALC_DR21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Nov-2021 11:49:20

DR2 = reshape([1.0,0.0,0.0,1.0],[2,2]);
