function DG2 = calc_Dg21(in1,uy,in3)
%CALC_DG21
%    DG2 = CALC_DG21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Nov-2021 11:49:20

DG2 = [0.0,-1.0];
