function DG1 = calc_Dg12(in1,uy,in3)
%CALC_DG12
%    DG1 = CALC_DG12(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 01:22:00

DG1 = [1.0,0.0];
