function f1 = calc_f1(in1,in2,in3)
%CALC_F1
%    F1 = CALC_F1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:00:23

g = in3(:,2);
m = in3(:,1);
u_x = in2(1,:);
u_y = in2(2,:);
x_dot = in1(3,:);
y_dot = in1(4,:);
t2 = 1.0./m;
f1 = [x_dot;y_dot;t2.*u_x;t2.*(u_y-g.*m)];
