function f1 = calc_f1(in1,uy,in3)
%CALC_F1
%    F1 = CALC_F1(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Nov-2021 11:49:20

g = in3(:,2);
m = in3(:,1);
y_dot = in1(2,:);
f1 = [y_dot;(uy-g.*m)./m];
