function A_lin1_disc = calc_A_lin1_disc(in1,uy,dt,in4)
%CALC_A_LIN1_DISC
%    A_LIN1_DISC = CALC_A_LIN1_DISC(IN1,UY,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 01:22:01

A_lin1_disc = reshape([1.0,0.0,dt,1.0],[2,2]);
