function DG2 = calc_Dg21(in1,in2,in3)
%CALC_DG21
%    DG2 = CALC_DG21(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:19:17

g = in3(:,2);
m = in3(:,1);
u_x = in2(1,:);
u_y = in2(2,:);
x = in1(1,:);
x_dot = in1(3,:);
y = in1(2,:);
y_dot = in1(4,:);
t2 = u_x.*x;
t3 = u_y.*y;
t4 = u_y.*5.0;
t5 = x.^2;
t6 = x_dot.^2;
t7 = y.^2;
t8 = y_dot.^2;
t9 = g.*m.*5.0;
t10 = g.*m.*y;
t12 = y.*1.0e+1;
t11 = -t4;
t13 = m.*t6;
t14 = m.*t8;
t15 = -t12;
t16 = -t10;
t17 = t5+t7+t15+2.5e+1;
t20 = t2+t3+t9+t11+t13+t14+t16;
t18 = 1.0./t17;
t19 = t18.^2;
DG2 = [(t18.*u_x)./2.0-t19.*t20.*x,(t18.*(u_y-g.*m))./2.0-(t19.*t20.*(y.*2.0-1.0e+1))./2.0,m.*t18.*x_dot,m.*t18.*y_dot];
