function B_lin1_disc = calc_B_lin1_disc(in1,in2,dt,in4)
%CALC_B_LIN1_DISC
%    B_LIN1_DISC = CALC_B_LIN1_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Nov-2021 22:19:18

m = in4(:,1);
t2 = 1.0./m;
t3 = dt.*t2;
B_lin1_disc = reshape([0.0,0.0,t3,0.0,0.0,0.0,0.0,t3],[4,2]);
